# Generated by Django 2.2 on 2020-01-04 02:26

import app01.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_auto_20200104_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myperson',
            name='image',
            field=models.ImageField(upload_to=app01.models.image_upload_to),
        ),
    ]
